# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React and Spring app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-spring:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: './server/build/libs'
          
  deploy-spring:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    needs: build-spring
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wordlink'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF35CDBE63A1450C94DF4F49ECC595EE }}
          package: '*SNAPSHOT.jar'

  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app

    steps:
     - uses: actions/checkout@v4

     - name: Authenticate
       run: git config --global user.name 'Github actions'

     - name: Authenticate 2
       run: git config --global user.email 'wongislandd@users.noreply.github.com'
     
     - name: Clean install
       run: npm install

     - name: Deploy web app
       run: npm run deplo
        
    
